name: random404
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9229391
title: miscellaneous musings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050507'
    - '#BEBDB6'
    - '#EBB46D'
    - '#CF7742'
    - '#303831'
  brandStrength: 1
  lightness: 0.6279355
  saturation: 0.06030044
  rhythmicContrast: 0.839562
purpose: []
